server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanceSchoolMicroservices/{application}
          force-pull: true
          username: DanceSchoolMicroservices
          password: DanceSchool8MS!

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true