server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanceSchoolMicroservices/{application}
          force-pull: true
          username: DanceSchoolMicroservices
          password: DanceSchool8MS!
        health:
          repositories:
            check:
              name: zuulschool
              profiles: kubernetes

management:
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true